[package]
name = "nom-derive"
description = "Custom derive nom parsers from struct"
version = "0.1.0"
license = "MIT/Apache-2.0"
keywords = ["parser","nom"]
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[dev-dependencies]
nom = "3.2.1"
pretty_assertions = "0.5.0"
