[package]
name = "nom-derive"
description = "Custom derive nom parsers from struct"
version = "0.1.0"
license = "MIT/Apache-2.0"
keywords = ["parser","nom"]
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
# syn = { version="0.15", features=["parsing","extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4"

[dev-dependencies]
nom = "4.0"
pretty_assertions = "0.5.0"
